apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-org1-example-com
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ca-org1-example-com
  template:
    metadata:
      labels:
        name: ca-org1-example-com
    spec:
      volumes:
      - name: fabricfiles
        persistentVolumeClaim:
          claimName: fabric-pvc

      containers:
      - name: ca-org1-example-com
        image: hyperledger/fabric-ca:amd64-1.4.4
        command: ["sh", "-c", "fabric-ca-server start --ca.certfile /fabric/crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem --ca.keyfile /fabric/crypto-config/peerOrganizations/org1.example.com/ca/f518fa72d70fdc3affa4dbe470ea0653d68495ed3f23cec8020cfc1e7a93ee6d_sk -b admin:adminpw -d"]
        env:
        - name: FABRIC_CA_HOME
          value: /fabric/hyperledger/fabric-ca-server
        - name: FABRIC_CA_SERVER_CA_NAME
          value: "ca-org1-example-com"
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "true"
        - name: FABRIC_CA_SERVER_TLS_CERTFILE
          value: /fabric/crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem
        - name: FABRIC_CA_SERVER_TLS_KEYFILE
          value: /fabric/crypto-config/peerOrganizations/org1.example.com/ca/f518fa72d70fdc3affa4dbe470ea0653d68495ed3f23cec8020cfc1e7a93ee6d_sk
        - name: FABRIC_CA_SERVER_PORT
          value: "7054" 
        volumeMounts:
        - mountPath: /fabric
          name: fabricfiles

---

apiVersion: v1
kind: Service
metadata:
  name: ca-org1-example-com
  labels:
    run: ca-org1-example-com
spec:
  type: ClusterIP
  selector:
    name: ca-org1-example-com
  ports:
  - protocol: TCP
    port: 7054
    targetPort: 7054
    name: grpcs

