apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-org3-example-com
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ca-org3-example-com
  template:
    metadata:
      labels:
        name: ca-org3-example-com
    spec:
      volumes:
      - name: fabricfiles
        persistentVolumeClaim:
          claimName: fabric-pvc

      containers:
      - name: ca-org3-example-com
        image: hyperledger/fabric-ca:amd64-1.4.4
        command: ["sh", "-c", "fabric-ca-server start --ca.certfile /fabric/crypto-config/peerOrganizations/org3.example.com/ca/ca.org3.example.com-cert.pem --ca.keyfile /fabric/crypto-config/peerOrganizations/org3.example.com/ca/e3623bd3ebdd63425bd6d3c50ac484823221b67be661dc011a178a25e6c0e6c9_sk -b admin:adminpw -d"]
        env:
        - name: FABRIC_CA_HOME
          value: /fabric/hyperledger/fabric-ca-server
        - name: FABRIC_CA_SERVER_CA_NAME
          value: "ca-org3-example-com"
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "true"
        - name: FABRIC_CA_SERVER_TLS_CERTFILE
          value: /fabric/crypto-config/peerOrganizations/org3.example.com/ca/ca.org3.example.com-cert.pem
        - name: FABRIC_CA_SERVER_TLS_KEYFILE
          value: /fabric/crypto-config/peerOrganizations/org3.example.com/ca/e3623bd3ebdd63425bd6d3c50ac484823221b67be661dc011a178a25e6c0e6c9_sk
        - name: FABRIC_CA_SERVER_PORT
          value: "7054" 
        volumeMounts:
        - mountPath: /fabric
          name: fabricfiles

---

apiVersion: v1
kind: Service
metadata:
  name: ca-org3-example-com
  labels:
    run: ca-org3-example-com
spec:
  type: ClusterIP
  selector:
    name: ca-org3-example-com
  ports:
  - protocol: TCP
    port: 7054
    targetPort: 7054
    name: grpcs

