apiVersion: v1
kind: Service
metadata:
  name: peer0-org3-example-com
  labels:
    run: peer0-org3-example-com
spec:
  type: ClusterIP 
  selector:
    name: peer0-org3-example-com
  ports:
  - protocol: TCP
    port: 7051
    name: grpcs
  - protocol: TCP
    port: 7053
    name: events
  - protocol: TCP
    port: 5984
    name: couchdb
  - protocol: TCP
    port: 9443
    name: operations
